### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by scottfwalter** [bclozel/gulp-bower-src#7]
I have this 

gulp.task('package', function () {
    bowerSrc()
        .pipe(gulp.dest('./dist'));
});

but when I run "gulp package" I get

package' errored after 231 μs
[13:57:16] TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at gulpBowerSrc (/Users/scott/Dropbox/sandbox/modernapp/node_modules/gulp-bower-src/index.js:89:31)
    at Gulp.<anonymous> (/Users/scott/Dropbox/sandbox/modernapp/gulpfile.js:71:5)
    at module.exports (/Users/scott/Dropbox/sandbox/modernapp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/scott/Dropbox/sandbox/modernapp/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/scott/Dropbox/sandbox/modernapp/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/scott/Dropbox/sandbox/modernapp/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)

**Comment by scottfwalter** [comment]
If you specify a directory in '.bowerrc' then all is right in the world.  Perhaps default to 'bower_components' if the directory property is not specified in .bowerrc
